fs.makeDir('/lib')
fs.makeDir('/lib/class')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/builtins.lua /lib/class/builtins.lua')
fs.makeDir('/lib/class/functional')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/functional/method.lua /lib/class/functional/method.lua')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/link.lua /lib/class/link.lua')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/object.lua /lib/class/object.lua')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/overloading.lua /lib/class/overloading.lua')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class/type.lua /lib/class/type.lua')
shell.run('wget https://raw.githubusercontent.com/MrVoustache/LuaPyOOP/refs/heads/main/source/class.lua /lib/class.lua')
